name: Build PKHeX

on:
  push:
    branches: [ "master" ] # 每次你向 master 分支推送代码时自动运行
  workflow_dispatch: # 在网页上添加一个“手动运行”的按钮

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 1. 下载你的代码
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: 2. 安装 .NET 环境
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x
          10.0.x
        dotnet-quality: 'preview'

    - name: 3. 开始编译 (Build)
      run: dotnet build PKHeX.sln -c Release

    - name: 4. 打包并上传生成的软件
      uses: actions/upload-artifact@v4
      with:
        name: PKHeX-zh-Release
        # 自动抓取 Release 文件夹下所有带有 net 和 windows 名字的文件夹内容
        path: PKHeX.WinForms/bin/Release/net*-windows/
